/********************************************************************
* FedConsumerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error FedConsumerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableFedConsumerDict();
extern void G__cpp_setup_inheritanceFedConsumerDict();
extern void G__cpp_setup_typetableFedConsumerDict();
extern void G__cpp_setup_memvarFedConsumerDict();
extern void G__cpp_setup_globalFedConsumerDict();
extern void G__cpp_setup_memfuncFedConsumerDict();
extern void G__cpp_setup_funcFedConsumerDict();
extern void G__set_cpp_environmentFedConsumerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "FedConsumer.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__FedConsumerDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__FedConsumerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__FedConsumerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FedConsumerDictLN_TList;
extern G__linked_taginfo G__FedConsumerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__FedConsumerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FedConsumerDictLN_TQObjSender;
extern G__linked_taginfo G__FedConsumerDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__FedConsumerDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__FedConsumerDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FedConsumerDictLN_TGLayoutHints;
extern G__linked_taginfo G__FedConsumerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__FedConsumerDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__FedConsumerDictLN_TGMainFrame;
extern G__linked_taginfo G__FedConsumerDictLN_TGButton;
extern G__linked_taginfo G__FedConsumerDictLN_TGCheckButton;
extern G__linked_taginfo G__FedConsumerDictLN_TCanvas;
extern G__linked_taginfo G__FedConsumerDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__FedConsumerDictLN_TGTextEntry;
extern G__linked_taginfo G__FedConsumerDictLN_TGComboBox;
extern G__linked_taginfo G__FedConsumerDictLN_TSocket;
extern G__linked_taginfo G__FedConsumerDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__FedConsumerDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FedConsumerDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__FedConsumerDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__FedConsumerDictLN_TH1D;
extern G__linked_taginfo G__FedConsumerDictLN_FedConsumer;

/* STUB derived class for protected member access */
